### ISSUE TITLE
Do not show vim help files in oldfiles list

### ISSUE THREAD

**Issue by sudormrfbin** [gpanders/vim-oldfiles#1]
In the `oldfiles` list by default all the files recently opened are shown, which means vim help files also show up. It'd be great if the plugin removed these items when showing the quickfix list. Right now I'm using `:Oldfiles! vim/runtime/doc/` to filter out the help files.

P.S. I love how simple this plugin is and that it doesn't try to reinvent the wheel :)

**Comment by gpanders** [comment]
You can now set the `g:oldfiles_blacklist` option to have it always filter items that match patterns in that option:
```vim
let g:oldfiles_blacklist = ['vim/runtime/doc/']
```

> P.S. I love how simple this plugin is and that it doesn't try to reinvent the wheel :)

I'm glad you think so! That was my intention from the beginning.

**Comment by sudormrfbin** [comment]
Thanks for implementing it so fast ! I was thinking about suppressing only the help files implicitly, but this is definitely more expressive and configurable. Thanks again !
