### ISSUE TITLE
An option to close Oldfiles buffer after opening a file?

### ISSUE THREAD

**Issue by JosefMontag** [gpanders/vim-oldfiles#2]
Thank you, this is a great improvement. (I used to use bro ol all the time and it sucked a bit.)

Would it be possible to allow for the Oldfiles buffer to close after opening a file? (Either as an option or default.)

I tried to figure this out but do not know enough vimscript to do that.

Thank you, 

Josef

**Comment by gpanders** [comment]
Adding more config options is not something I want to do, as an important design goal for this plugin is to keep it as minimal and simple as possible. Similarly, I don't want to add "special case" functionality such as auto closing the quickfix list. vim-oldfiles does exactly two things: 1) keep the `v:oldfiles` variable up-to-date and 2) put the output of `:oldfiles` in the quickfix list. Any functionality or customization beyond that should be done using the tools that Vim itself provides.

That said, I completely understand the desire to have the quickfix list auto close upon making a selection. Unlike other uses of the quickfix list, you won't typically want to keep the list of oldfiles open after you've made your selection. You can use the following snippet in your vimrc to achieve this:

```vim
augroup oldfiles
    autocmd!
    autocmd FileType qf if w:quickfix_title =~# 'Oldfiles' | nnoremap <buffer> <CR> <CR>:cclose<CR> | endif
augroup END
```

Let me explain what this does:

```vim
augroup oldfiles
    autocmd!
```

This creates a new autocmd group called `oldfiles` and clears any existing autocmds already existing in the group. This ensures that if the file is sourced more than once, you don't end up with duplicate autocmds.

```vim
autocmd FileType qf
```

This creates a new "autocmd" for the file type `qf` (i.e. the quickfix list). The following command will trigger anytime a quickfix list buffer is opened.

```vim
if w:quickfix_title =~# 'Oldfiles' | nnoremap <buffer> <CR> <CR>:cclose<CR> | endif
```

When a new quickfix buffer is opened, check if the window title matches "Oldfiles". If it does, remap the Return key to also close the quickfix window (so this will close the quickfix window after you make a selection).

**EDIT:** Updated the snippet above.

**Comment by gpanders** [comment]
I added this to the [FAQ](https://github.com/gpanders/vim-oldfiles#faq) in the README.
