### ISSUE TITLE
"No matching autocommands" after :Oldfiles

### ISSUE THREAD

**Issue by LauriMauranen** [gpanders/vim-oldfiles#3]
Hey and thanks for nice little plugin. I'm amazed this repo has no more stars!

When I run command :Oldfiles I get message:

```
No matching autocommands
"[Quickfix List]" 50 lines --2%--
```

Then I can just press Enter and everything works fine. Do you have ideas why this happens?

My vim version is 8.1. I noticed my vim is compiled without +browse, I wonder does it have anything to with this?

**Comment by LauriMauranen** [comment]
Ok and I just now noticed that :Oldfiles only gives file history from current vim session, so it does not load viminfo properly.

**Comment by gpanders** [comment]
~~Please try again with all other plugins disabled and let me know if the issue persists. The `:Oldfiles` command does nothing but read the `v:oldfiles` variable out of Vim, it does not attempt to load viminfo at all, so it seems likely that another plugin is interfering.~~

Nevermind, I can reproduce this issue in Vim 8.2 as well. Looking into it now.

**Comment by gpanders** [comment]
Thanks for bringing the "No matching autocommands" issue up, I was able to reproduce this and just pushed a fix.

**Comment by gpanders** [comment]
Ok I believe I found the problem and just pushed a solution. Please pull the most recent changes and let me know if you're still seeing the problem.

**Comment by LauriMauranen** [comment]
Nice no message and file history is there:)

**Comment by gpanders** [comment]
Thanks for reporting the bug!
