### ISSUE TITLE
Open file in same window

### ISSUE THREAD

**Issue by LauriMauranen** [gpanders/vim-oldfiles#4]
Hey, I noticed that if I have two windows vertically open, `:Oldfiles` opens file always in rigth window. I think it would be nice if file opened in same window where `:Oldfiles` is run.

**Comment by gpanders** [comment]
Oldfiles doesn't handle opening windows at all, it simply populates the quickfix list. At that point, where a window is opened is entirely up to Vim.

Try searching or asking on some of the Vim support channels on ways to do this.
