### ISSUE TITLE
Quickfix list for oldfiles always opens in right most vertical split

### ISSUE THREAD

**Issue by luetage** [gpanders/vim-oldfiles#5]
Hey! First and foremost, great plugin, it’s really helpful. The single issue I have with it is that the quickfix list always opens as split of the right most vertical split, no matter the window configuration and active window. Bascially it always opens on bottom right. The selected oldfiles entry will also open in the right most vertical split then. I don’t have anything in my config that would warrant such a behaviour. A regular quickfix list opens as split of the currently active vertical split. I’m using latest stable neovim 0.5, maybe that’s the issue.

**Comment by gpanders** [comment]
This is the default behavior for both Vim and Neovim:

```
$ nvim -u NONE +vsplit +copen
```

opens the quickfix list in the right vertical split. vim-oldfiles isn't doing anything special.

You can modify where the quickfix list opens with the `:leftabove`, `:rightbelow`, `:topleft`, and `:botright` commands. For example, try

```vim
:botright Oldfiles
```

**Comment by luetage** [comment]
You are absolutely right, sorry for wasting your time. Setting it to `:below Oldfiles` does the trick.
